export const CATEGORIES = {
  income: ["Salary", "Investments", "Freelance", "Gifts", "Other"],
  expense: [
    "Food",
    "Housing",
    "Transportation",
    "Healthcare",
    "Entertainment",
    "Education",
    "Shopping",
    "Subscriptions",
    "Other",
  ],
};

export const PAYMENT_METHODS = [
  "Credit Card",
  "Debit Card",
  "Pix",
  "Cash",
  "Bank Transfer",
  "Boleto",
];

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

// Keywords para sugestão automática de categoria
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  // Expense categories
  Food: [
    "mercado",
    "supermercado",
    "hortifruti",
    "açougue",
    "padaria",
    "restaurante",
    "lanchonete",
    "ifood",
    "rappi",
    "uber eats",
    "delivery",
    "almoço",
    "jantar",
    "café",
    "coffee",
    "starbucks",
    "mcdonald",
    "burger",
    "pizza",
    "sushi",
    "feira",
    "verduras",
    "frutas",
    "carrefour",
    "extra",
    "pão de açúcar",
    "atacadão",
    "assaí",
    "bistek",
    "angeloni",
  ],
  Transportation: [
    "uber",
    "99",
    "cabify",
    "táxi",
    "taxi",
    "gasolina",
    "combustível",
    "posto",
    "estacionamento",
    "pedágio",
    "ipva",
    "seguro auto",
    "manutenção carro",
    "oficina",
    "pneu",
    "troca óleo",
    "metro",
    "metrô",
    "ônibus",
    "onibus",
    "passagem",
    "bilhete",
    "vlt",
    "brt",
  ],
  Healthcare: [
    "farmácia",
    "farmacia",
    "drogaria",
    "remédio",
    "medicamento",
    "médico",
    "consulta",
    "exame",
    "hospital",
    "clínica",
    "dentista",
    "psicólogo",
    "terapia",
    "plano de saúde",
    "unimed",
    "bradesco saúde",
    "droga raia",
    "drogasil",
    "pague menos",
    "panvel",
  ],
  Entertainment: [
    "cinema",
    "teatro",
    "show",
    "ingresso",
    "netflix",
    "spotify",
    "disney",
    "amazon prime",
    "hbo",
    "youtube premium",
    "twitch",
    "game",
    "jogo",
    "playstation",
    "xbox",
    "steam",
    "bar",
    "balada",
    "festa",
    "parque",
    "viagem",
    "hotel",
    "airbnb",
    "lazer",
  ],
  Education: [
    "curso",
    "faculdade",
    "universidade",
    "escola",
    "livro",
    "udemy",
    "coursera",
    "alura",
    "rocketseat",
    "material escolar",
    "mensalidade",
    "matrícula",
    "apostila",
    "inglês",
    "idioma",
  ],
  Shopping: [
    "roupa",
    "sapato",
    "tênis",
    "camisa",
    "calça",
    "vestido",
    "shopping",
    "loja",
    "renner",
    "c&a",
    "riachuelo",
    "zara",
    "shein",
    "aliexpress",
    "amazon",
    "mercado livre",
    "magalu",
    "americanas",
    "shopee",
    "presente",
  ],
  Subscriptions: [
    "assinatura",
    "mensalidade",
    "netflix",
    "spotify",
    "disney+",
    "hbo max",
    "amazon prime",
    "youtube premium",
    "apple music",
    "deezer",
    "gym",
    "academia",
    "smartfit",
    "plano",
    "telefone",
    "internet",
    "celular",
  ],
  Housing: [
    "aluguel",
    "condomínio",
    "iptu",
    "água",
    "luz",
    "energia",
    "gás",
    "internet",
    "wifi",
    "móveis",
    "decoração",
    "reforma",
    "conserto",
    "eletricista",
    "encanador",
    "faxina",
    "limpeza",
  ],
  // Income categories
  Salary: [
    "salário",
    "salario",
    "pagamento",
    "holerite",
    "contracheque",
    "ordenado",
    "remuneração",
    "13º",
    "décimo terceiro",
    "férias",
  ],
  Investments: [
    "dividendos",
    "rendimento",
    "juros",
    "ações",
    "fii",
    "renda fixa",
    "tesouro",
    "cdb",
    "lci",
    "lca",
    "lucro",
    "investimento",
  ],
  Freelance: [
    "freelance",
    "freela",
    "projeto",
    "consultoria",
    "serviço",
    "trabalho extra",
    "comissão",
    "bônus",
    "bonus",
  ],
  Gifts: [
    "presente",
    "gift",
    "doação",
    "herança",
    "prêmio",
    "sorteio",
    "cashback",
    "reembolso",
    "devolução",
  ],
};

// Valores rápidos comuns para despesas
export const QUICK_AMOUNTS = [10, 20, 50, 100, 200, 500];

// Botão "Nova Transação" — mesmo tamanho e estilo em todas as telas
export const CREATE_TRANSACTION_BUTTON = {
  label: "Nova Transação",
  sx: { height: 40, borderRadius: "20px", px: 2.5 },
} as const;
